# Generated by Django 5.2.7 on 2025-10-31 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_business_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Sender's name", max_length=200)),
                (
                    "email",
                    models.EmailField(
                        help_text="Sender's email address", max_length=254
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Message subject", max_length=300),
                ),
                (
                    "message",
                    models.TextField(help_text="Message content", max_length=5000),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="Sender's IP address for security tracking"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, help_text="Browser user agent", max_length=500
                    ),
                ),
                (
                    "honeypot",
                    models.CharField(
                        blank=True,
                        help_text="Honeypot field - should be empty",
                        max_length=100,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_read",
                    models.BooleanField(
                        default=False, help_text="Has this been read by an admin?"
                    ),
                ),
                (
                    "is_responded",
                    models.BooleanField(
                        default=False, help_text="Has this been responded to?"
                    ),
                ),
                (
                    "is_spam",
                    models.BooleanField(default=False, help_text="Flagged as spam"),
                ),
                (
                    "response_notes",
                    models.TextField(
                        blank=True, help_text="Admin notes about response"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["-submitted_at"], name="core_contac_submitt_17c262_idx"
                    ),
                    models.Index(
                        fields=["is_read", "is_spam"],
                        name="core_contac_is_read_c5c943_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "submitted_at"],
                        name="core_contac_ip_addr_1c7add_idx",
                    ),
                ],
            },
        ),
    ]
