# Generated by Django 5.2.7 on 2025-10-31 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Story title", max_length=200)),
                (
                    "author",
                    models.CharField(
                        help_text="Original author (e.g., Edgar Allan Poe)",
                        max_length=100,
                    ),
                ),
                (
                    "original_text",
                    models.TextField(blank=True, help_text="Original unmodified text"),
                ),
                (
                    "template_text",
                    models.TextField(
                        help_text="Text with placeholders like [NOUN], [ADJECTIVE], [VERB], [ADVERB]"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy (5 blanks)"),
                            ("medium", "Medium (10 blanks)"),
                            ("hard", "Hard (15+ blanks)"),
                        ],
                        default="easy",
                        max_length=20,
                    ),
                ),
                (
                    "word_count",
                    models.IntegerField(
                        default=5, help_text="Number of blanks to fill"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Show in template list"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["difficulty", "title"],
            },
        ),
        migrations.CreateModel(
            name="CompletedMadLib",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed_text",
                    models.TextField(help_text="Story with blanks filled in"),
                ),
                (
                    "user_words",
                    models.JSONField(
                        help_text="Dictionary of words used: {'NOUN_1': 'ghost', ...}"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Show in public gallery"
                    ),
                ),
                (
                    "share_code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique code for sharing",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "view_count",
                    models.IntegerField(default=0, help_text="Number of times viewed"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this (optional for anonymous play)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_madlibs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="games.storytemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VocabularyWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word",
                    models.CharField(help_text="The vocabulary word", max_length=100),
                ),
                (
                    "part_of_speech",
                    models.CharField(
                        choices=[
                            ("noun", "Noun"),
                            ("verb", "Verb"),
                            ("adjective", "Adjective"),
                            ("adverb", "Adverb"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("halloween", "Halloween"),
                            ("spooky", "Spooky"),
                            ("classic", "Classic"),
                            ("silly", "Silly"),
                        ],
                        default="halloween",
                        max_length=50,
                    ),
                ),
                (
                    "is_kid_friendly",
                    models.BooleanField(
                        default=True, help_text="Appropriate for children"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["part_of_speech", "word"],
                "unique_together": {("word", "part_of_speech")},
            },
        ),
    ]
